print("twinkle twinkle little star")
print("how i wonder how you are")
print("up above the world so high")
print("like a diamond in the sky")
print("twinkle twinkle little star")
print("how i wonder how you are")